# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: .next

jobs:
# Please do not rename this job
  build-project:
    name: build 2.0
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v20.x

      - name: Build Node assets
        env:
          CI: true
          DATABASE_URL: postgresql://neondb_owner:npg_KdMl5oT8WAak@ep-lingering-breeze-ab64iy3b.eu-west-2.aws.neon.tech/neondb?sslmode=require
          NEXT_PUBLIC_SITE_URL: https://fountainuk.co.uk
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install --legacy-peer-deps
          npx prisma generate
          npx prisma db push
          npx tsx prisma/seed.ts
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 405d9d2c-312c-4a06-abb1-d927f9248267
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/2.0/config.yaml
          action: upload
